title: 1st Workshop on Active Defense and Deception (AD&D) <br> June 10th, 2022
url: "adnd.work"

markdown: kramdown

nav:
    - {name: CFP, link: '/index.html#call-for-contributions'}
    - {name: Submission, link: '/index.html#submission-guidelines'}
    - {name: Accepted Papers, link: '/accepted_papers/'}
    - {name: Program, link: '/program/'}
    


tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

