title: ADnD
url: "https://billypragsec.github.io"

markdown: kramdown

nav:
    - {name: CFP, link: '/'}
    - {name: 2022, link: '/ADNDprogram22/'}


tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

