title: 2nd Workshop on Active Defense and Deception (AD&D) <br> July 3-7, 2023 Delft
url: "adnd.work"

markdown: kramdown

nav:
    - {name: CFP, link: '/index.html#call-for-contributions'}
    - {name: Submission, link: '/index.html#submission-guidelines'}
    - {name: Program, link: '/program/'}
    - {name: ADnD 2022 (Archive), link: '/archive/'}
    


tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

